name: ci_cd
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite:///:memory:"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python --version
      - run: python -m pip install -r requirements.txt
      - run: ruff check .
      - run: python -m pytest
  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-service:${{ github.ref_name }} -f docker/Dockerfile .
      - uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-service:${{ github.ref_name }}
